steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: acr
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      repository: parsoid
      tags: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - bash: |
      sed -i .bak k8s/deploy.yaml
        -e "s@%IMAGE%@scouterna.azurecr.io/parsoid:$BUILD_SOURCEBRANCHNAME-$BUILD_SOURCEVERSION"
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'parsoid/k8s'
      ArtifactName: 'j21parsoid-k8s'
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables.updated, 'true'))
