steps:
  - bash: |
      docker build . -t foo:$(git rev-list -1 HEAD)
    workingDirectory: services/foo
    displayName: Build Docker image
    condition: and(succeeded(), eq(variables.updated, 'true'))
