apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    plugins.konghq.com: office-oauth
    kubernetes.io/ingress.class: "kong"
  name: mediawiki
spec:
  rules:
  {{ range .Values.domains }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: template
          servicePort: 8080
  {{- end }}
  tls:
  - hosts:
    {{ range .Values.domains }}
    - {{ . }}
    {{- end }}
    secretName: template-tls
