apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    konghq.com/plugins: office-oauth
    kubernetes.io/ingress.class: "kong"
  name: mediawiki
spec:
  rules:
  {{ range .Values.domains }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
          service:
            name: template
            port:
              number: 8080
  {{- end }}
  tls:
  - hosts:
    {{ range .Values.domains }}
    - {{ . }}
    {{- end }}
    secretName: template-tls
