apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: download-aboutme
spec:
  schedule: "0 */8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-aboutme
            image: %DOWNLOADER_IMAGE%
            imagePullPolicy: IfNotPresent
            volumemounts:
              - mountPath: /aboutme-data
                name: aboutme-data
          restartPolicy: OnFailure
          volumes:
            - name: aboutme-data
              persistentVolumeClaim:
                claimName: aboutme-data