apiVersion: extensions/v1
kind: Deployment
metadata:
  annotations: {}
  name: facelist
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: facelist
    spec:
      containers:
        - image: %IMAGE%
          imagePullPolicy: Always
          name: facelist
          volumeMounts:
            - mountPath: "/"
              name: facelist-config
              readOnly: true
      volumes:
        - name: facelist-config
          secret:
            secretName: facelist-config
