apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  name: facelist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facelist
  template:
    metadata:
      labels:
        app: facelist
    spec:
      containers:
        - image: %IMAGE%
          imagePullPolicy: Always
          name: facelist
          volumeMounts:
            - mountPath: "/"
              name: facelist-config
              readOnly: true
            - mountPath: /img
              name: img
      volumes:
        - name: facelist-config
          secret:
            secretName: facelist-config
        - name: img
          persistentVolumeClaim:
            claimName: img
