apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  name: facelist
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: facelist
    spec:
      containers:
        image: %IMAGE%
        imagePullPolicy: Always
        name: facelist
        volumeMounts:
          - mountPath: "/"
            name: facelist.yaml
            readOnly: true
      volumes:
        - name: facelist.yaml
          secret:
            secretName: facelist-config
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: facelist
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: facelist
