---
parameters:
  serviceName: ''
  subPath: ''
steps:
  - task: HelmInstaller@1
    displayName: Helm installer
    inputs:
      helmVersionToInstall: latest
  - task: Bash@3
    displayName: Helm lint
    inputs:
      targetType: 'inline'
      script: helm lint ${{ parameters.subPath }} --values ${{ parameters.subPath }}/values/production.yaml
  - task: HelmDeploy@0
    displayName: Helm upgrade
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'minecraft'
      namespace: 'minecraft'
      command: upgrade
      chartType: filepath
      chartPath: charts/minecraft
      releaseName: minecraft
      install: true
      valueFile: charts/minecraft/values/production.yaml
      waitForExecution: false
    condition: or(and(succeeded(), eq(variables.updated, 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master')), eq(variables.forcerebuild, 'true'))
