---
apiVersion: v1
data:
  MEDIAWIKI_BASE_URL: {{ printf "https://%s" (first .Values.domains) }}
  MEDIAWIKI_EMAIL: {{ printf "apache@%s" (first .Values.domains) }}
  MEDIAWIKI_ADMIN_PASS: {{ .Values.adminpass | default "admin" }}
  MEDIAWIKI_ADMIN_USER: {{ .Values.adminuser | default "admin" }}
  MEDIAWIKI_DB_HOST: wikidb
  MEDIAWIKI_DB_PORT: "3306"
  MEDIAWIKI_DB_TYPE: mysql
  MEDIAWIKI_SITE_LANG: sv
  MEDIAWIKI_SITE_NAME: Jamboree21 wiki
  MEDIAWIKI_SITE_SERVER: {{ .Values.domain }}
  MEDIAWIKI_UPDATE: "false"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: mediawiki
  name: mediawiki-env
