apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    konghq.com/plugins: office-oauth
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
  name: mediawiki
spec:
  rules:
  {{ range .Values.domains }}
  - host: {{ . }}
    http:
      paths:
      - path: /parsoid
        backend:
          serviceName: parsoid
          servicePort: 8142
      - path: /
        backend:
          serviceName: mediawiki
          servicePort: 80
  {{- end }}
  tls:
  - hosts:
    {{ range .Values.domains }}
    - {{ . }}
    {{- end }}
    secretName: wiki-tls
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: mediawiki
route:
  strip_path: true
