---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: wikidata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data.capacity | default "16Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: wikiimages
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.images.capacity | default "1Gi" }}
  storageClassName: {{ .Values.storage.images.className | default "azurefile" }}
