---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: mediawiki
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mediawiki
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mariadb
  name: wikidb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
