---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: scoutwisedata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data.capacity | default "16Gi" }}
