steps:
  - bash: |
      docker build . -t scouterna.azurecr.io/mediawiki:$BUILD_SOURCEBRANCHNAME-$BUILD_SOURCEVERSION
    workingDirectory: wiki
    displayName: Build mediawiki docker image
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - task: Docker@2
    inputs:
      containerRegistry: 'acr'
      repository: $(Build.Repository.Name)
      command: 'push'
      tags: '$(Build.SourceBranchName)-$(Build.SourceVersion)'
    displayName: Push mediawiki docker image
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - bash: |
      sed -i .bak k8s/mediawiki.yaml \
        -e "s@%IMAGE%@scouterna.azurecr.io/mediawiki:$BUILD_SOURCEBRANCHNAME-$BUILD_SOURCEVERSION"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'wiki/k8s'
      ArtifactName: 'j21wiki-k8s'
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables.updated, 'true'))
