parameters:
  - name: serviceName
    type: string
    default: ''
  - name: subPath
    type: string
    default: ''
  - name: stepsTemplate
    type: string
    default: .azure-pipelines/templates/defaultbuild.yaml

jobs:
  - job: ${{ format('build_{0}', replace(parameters.serviceName, '-', '_')) }}
    displayName: ${{ format('Build {0}', parameters.serviceName) }}
    pool:
      vmImage: ubuntu-18.04
    steps:
      - checkout: self
        submodules: true
        persistCredentials: true
      - template: check-update-status.step.yaml  
        parameters:
          serviceName: ${{ parameters.serviceName }}
          subPath: ${{ parameters.subPath }}
      - template:  ${{ format('{0}/{1}', variables.Build.SourcesDirectory, parameters.stepsTemplate) }}
        parameters:
          serviceName: ${{ parameters.serviceName }}
          subPath: ${{ parameters.subPath }}
      - template: tag-build.step.yaml
        parameters:
          serviceName: ${{ parameters.serviceName }}
          subPath: ${{ parameters.subPath }}
