---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planera
  template:
    metadata:
      labels:
        app: planera
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: environment
        - env:
            - name: MICROSOFT_GRAPH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: microsoft-password
                  name: planera-credentials
            - name: WU_SECRET
              valueFrom:
                secretKeyRef:
                  key: wikiupdate-secret
                  name: planera-credentials
          image: {{ .Values.image | default "scouterna.azurecr.io/planera" }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: app

