apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  name: parsoid
  namespace: jamboree21
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: parsoid
    spec:
      containers:
      - env:
        - name: PARSOID_DOMAIN
          value: https://wiki.internal.jamboree.se.scouterna.net/api.php
          image: thenets/parsoid:0.10
        imagePullPolicy: IfNotPresent
        name: parsoid
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: parsoid
  namespace: jamboree21
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: parsoid
