version: '3.9'

services:
  web:
    build:
      context: web
    ports:
      - '8081:80'
    # command: [nginx-debug, '-g', 'daemon off;']

  api:
    build:
      context: api
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    stop_signal: SIGINT
    ports:
      - '8080:5000'

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init-scoutwise-db.sh:/docker-entrypoint-initdb.d/init-scoutwise-db.sh:ro
      - ./db/scoutwise_backup:/backup/scoutwise
    ports:
      - 5432:5432
volumes:
  db:
    driver: local