version: '3.9'

services:
  web:
    build:
      context: web
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - api
    # command: [nginx-debug, '-g', 'daemon off;']

  api:
    build:
      context: api
    restart: always
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    stop_signal: SIGINT
    ports:
      - '8080:5000'
    depends_on:
      - db

  copywise:
    build:
      context: copywise
    profiles:
      - tools
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      PRIVATE_KEY: ${PRIVATE_KEY}
      WISE_APITOKEN: ${WISE_APITOKEN}
      WISE_PROFILEID: ${WISE_PROFILEID}
      WISE_ACCOUNTID: ${WISE_ACCOUNTID}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init-scoutwise-db.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432
volumes:
  db:
    driver: local