apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: ClusterIP
  ports:
    - port: 25565
      targetPort: 25565
      protocol: UDP
  selector:
    app: minecraft-server
