apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: minecraft-server
