apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  name: {{ .Values.name }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: 25565
        path: /
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.name }}
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ .Values.name }}
route:
  strip_path: true
