apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: wikidata
  namespace: jamboree21
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  name: mariadb
  namespace: jamboree21
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: postgres_db
              name: db-credentials
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: postgres_user
              name: db-credentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: db-credentials
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: db-credentials
        image: mariadb:10
        imagePullPolicy: IfNotPresent
        name: mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: wikidata
      volumes:
      - name: wikidata
        persistentVolumeClaim:
          claimName: wikidata
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mariadb
  name: wikidb
  namespace: jamboree21
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
