apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: wikiimages
  namespace: jamboree21
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  name: mediawiki
  namespace: jamboree21
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - env:
        - name: MEDIAWIKI_BASE_URL
          value: "https://wiki.internal.jamboree.se.webservices.scouterna.net"
        - name: MEDIAWIKI_EMAIL
          value: "apache@wiki.jamboree.se.staging.scouterna.net"
        - name: MEDIAWIKI_DB_NAME
          valueFrom:
            secretKeyRef:
              key: postgres_db
              name: db-credentials
        - name: MEDIAWIKI_DB_USER
          valueFrom:
            secretKeyRef:
              key: postgres_user
              name: db-credentials
        - name: MEDIAWIKI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: db-credentials
        - name: MEDIAWIKI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: mediawiki_secret_key
              name: mediawiki-secrets
        - name: MEDIAWIKI_UPGRADE_KEY
          valueFrom:
            secretKeyRef:
              key: mediawiki_upgrade_key
              name: mediawiki-secrets
        - name: SAML_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: saml_admin_password
              name: saml-credentials
        - name: SAML_SECRET_SALT
          valueFrom:
            secretKeyRef:
              key: saml_secret_salt
              name: saml-credentials
        - name: SAML_APP_ID
          valueFrom:
            secretKeyRef:
              key: saml_app_id
              name: saml-credentials
        - name: SAML_IDP
          valueFrom:
            secretKeyRef:
              key: saml_idp
              name: saml-credentials
        envFrom:
        - configMapRef:
            name: mediawiki-env
        image: %IMAGE%
        imagePullPolicy: Always
        name: wiki
        volumeMounts:
        - mountPath: /var/www/html/images
          name: images
      volumes:
      - name: images
        persistentVolumeClaim:
          claimName: wikiimages
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: mediawiki
  namespace: jamboree21
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mediawiki
